version: '3.8'
services:
  db:
    container_name: pg_container
    image: postgres
    restart: always
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: todo_db
    ports:
      - '8080:5432'

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '5050:80'

  server:
    build: .
    depends_on:
      - db
    ports:
      - 4000:4000
    command: >
      bash -c "
      yarn build 
      && node dist/index.js"
