version: '3.8'
services:
  db:
    container_name: pg_container
    image: postgres
    restart: always
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 8080:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PSWD}
      POSTGRES_DB: ${DB_NAME}

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_AMDIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PSWD}
    ports:
      - '${PG_ADMIN_PORT}:80'

  server:
    build: .
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - ${PORT}:${PORT}
    command: >
      bash -c "
      yarn build 
      && node dist/index.js"
